"""add_swim_and_networth_tables

Revision ID: 6aef75f4e5aa
Revises:
Create Date: 2026-02-22 16:41:45.024058

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6aef75f4e5aa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nw_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("institution", sa.String(length=255), nullable=True),
        sa.Column("account_type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nw_account_id"), "nw_account", ["id"], unique=False)
    op.create_table(
        "nw_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_date"),
    )
    op.create_index(op.f("ix_nw_snapshot_id"), "nw_snapshot", ["id"], unique=False)
    op.create_table(
        "swim_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("stroke", sa.String(length=50), nullable=False),
        sa.Column("pool_type", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_swim_event_id"), "swim_event", ["id"], unique=False)
    op.create_table(
        "swim_meet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_swim_meet_id"), "swim_meet", ["id"], unique=False)
    op.create_table(
        "swimmer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("team_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_swimmer_id"), "swimmer", ["id"], unique=False)
    op.create_table(
        "nw_snapshot_balance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["nw_account.id"],
        ),
        sa.ForeignKeyConstraint(["snapshot_id"], ["nw_snapshot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nw_snapshot_balance_id"), "nw_snapshot_balance", ["id"], unique=False)
    op.create_table(
        "swim_time",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("swimmer_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("meet_id", sa.Integer(), nullable=True),
        sa.Column("time_seconds", sa.Float(), nullable=False),
        sa.Column("recorded_date", sa.Date(), nullable=False),
        sa.Column("pool_type", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_pr", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["swim_event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meet_id"],
            ["swim_meet.id"],
        ),
        sa.ForeignKeyConstraint(
            ["swimmer_id"],
            ["swimmer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_swim_time_id"), "swim_time", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_swim_time_id"), table_name="swim_time")
    op.drop_table("swim_time")
    op.drop_index(op.f("ix_nw_snapshot_balance_id"), table_name="nw_snapshot_balance")
    op.drop_table("nw_snapshot_balance")
    op.drop_index(op.f("ix_swimmer_id"), table_name="swimmer")
    op.drop_table("swimmer")
    op.drop_index(op.f("ix_swim_meet_id"), table_name="swim_meet")
    op.drop_table("swim_meet")
    op.drop_index(op.f("ix_swim_event_id"), table_name="swim_event")
    op.drop_table("swim_event")
    op.drop_index(op.f("ix_nw_snapshot_id"), table_name="nw_snapshot")
    op.drop_table("nw_snapshot")
    op.drop_index(op.f("ix_nw_account_id"), table_name="nw_account")
    op.drop_table("nw_account")
    # ### end Alembic commands ###
