"""add_leg_type_and_strategy_group

Revision ID: 8a04904394df
Revises: 83c9f3a4559d
Create Date: 2026-02-27 10:09:56.378463

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a04904394df"
down_revision: str | Sequence[str] | None = "83c9f3a4559d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategy_group",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_sub", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategy_group_user_sub"), "strategy_group", ["user_sub"], unique=False
    )
    op.add_column("transaction", sa.Column("leg_type", sa.String(length=10), nullable=True))
    op.add_column(
        "transaction", sa.Column("strategy_group_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_transaction_strategy_group_id"), "transaction", ["strategy_group_id"], unique=False
    )
    op.create_foreign_key(
        None, "transaction", "strategy_group", ["strategy_group_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("transaction", "strategy_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column("strategy_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.drop_index(op.f("ix_transaction_strategy_group_id"), table_name="transaction")
    op.drop_column("transaction", "strategy_group_id")
    op.drop_column("transaction", "leg_type")
    op.drop_index(op.f("ix_strategy_group_user_sub"), table_name="strategy_group")
    op.drop_table("strategy_group")
    # ### end Alembic commands ###
